# Generated by Django 4.0.3 on 2023-10-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
